mt6765-common: proprietary-files: Add missing `vendor.mediatek.hardware.meta`
error: vendor/samsung/mt6765-common/Android.bp:18011:1: "meta_tst" depends on undefined module "vendor.mediatek.hardware.meta@1.0".

Change-Id: Ie3441ae201d4ebffc54c807e5c7ca45a40950541
Signed-off-by: jmpfbmx <jmpf.bmx@gmail.com>